### ISSUE TITLE
Message aggregation executed when only one message is recieved

### ISSUE THREAD

**Issue by mmoerdijk** [ros-industrial-attic/industrial_experimental#10]
I'm experimenting with the IRCv2 using a 'joint_map' with only one move group defined as follows:

```
controller_joint_map:
 - group: 1
   ns: "/festo"
   joints: [ 'joint_1', 'joint_2', 'joint_3', 'joint_4', 'joint_5', 'joint_6', 'joint_7']
```

and I'm having some difficulties with the robot_state node. It is my understanding that it should relay the status messages from the robot server to the `/<namespace/robotstatus ` topic. This topic does publish messages but there are not the same as the one send from the robot server. Using gbd I see that the messages are correctly received as simple messages but something goes wrong during the conversion to a rosmessage.

I tracked it down to line [line 259](https://github.com/ros-industrial/industrial_experimental/blob/indigo-devel/IRC_v2/industrial_robot_client/src/v2/robot_status_relay_handler.cpp#L259) of `robot_status_relay_handler.cpp`. There a check is made on how many namespaces there are in the `out` variable with the same namespace at the incoming message, if this is other than zero it is tried to aggregate the status message. 

But as I understand the number of namespaces is never zero because there is already one entry in the out variable with the same name space when the code on line 259 is first called. This however is just an "empty" message (initialized at line 88 of `robot_status_relay_handler.cpp`). Where everything except the ns and stamp are 0

This means that the code always tries to aggregate the empty message with the new "real" message. This results in undefined and incorrect behavior. 

@JeremyZoss did it understand it correctly or am I misinterpreting the code

**Comment by JeremyZoss** [comment]
I don't think the initialization at line 88 should create any entries in the `status_msgs` (aka. `out`) map.  I think the bug is in line 256: if the namespace does not already exist, the map's `[]` operator will create a new map entry for the specified namespace, using the default constructor.  This line would create valid values for the namespace and timestamp, but leave default values (typically `0`) for the remaining RobotStatus data.  For the `mode` field, this will be an invalid value, and other fields will probably default to `FALSE`.

As you saw, this means that the check in line 259 will never return 0, and will always trigger the `aggregate` method.  The default aggregate behavior is to return values of `UNKNOWN` if the new group's status values don't match the overall namespace's status value.  So, you're probably seeing a mix of UNKNOWN and valid values, depending on your robot's state.

I think there should be an easy test: comment out line 256 for now (this is only a minor feature).  If that produces the expected behavior, then I'll send a pull request to fix this bug.

Thanks for the feedback!

**Comment by gavanderhoorn** [comment]
I'm not sure, but my local version of these packages looks like it includes a commit that fixes exactly this issue:

``` patch
index 47d7b5a..89f61b3 100644
--- a/industrial_robot_client/src/v2/robot_status_relay_handler.cpp
+++ b/industrial_robot_client/src/v2/robot_status_relay_handler.cpp
@@ -252,14 +252,17 @@ bool RobotStatusRelayHandler::aggregate(const std::map<int, StatusMsg>&in,
       if (this->joint_map_[map_idx].group_id != group_id)
         continue;

-      // keep the latest timestamp
-      out[ns].header.stamp = std::max(in_msg.header.stamp, out[ns].header.stamp);
-
       // aggregate with existing messages
       if (out.count(ns)==0)
+      {
         out[ns] = in_msg;
+      }
       else
+      {
         out[ns] = aggregate(in_msg, out[ns]);
+        // keep the latest timestamp
+        out[ns].header.stamp = std::max(in_msg.header.stamp, out[ns].header.stamp);
+      }
     }
   }
```

With the following comment:

> robot_client: fix always aggregating incoming DynGrpStatus with all-zeros RobotStatus msgs.
> 
> The 'element access' operator will insert a new element (using the default ctor) into the map if the key given to it does not exist. This caused an all-zeros RobotStatus msg to always exist, even if no previous conversion of a DynGrpStatusGroup for a particular namespace had already been done.
> 
> The second overload of 'aggregate(..)' then compared that all-zeros msg with the actual converted msg, but as most fields would not have equal values, would set them to UNKNOWN.
> 
> Relocating the timestamp comparison avoids inserting the default element and makes both 'aggregate(..)'s work as expected again.

@JeremyZoss: would appear this never got merged in on your side?

**Comment by gavanderhoorn** [comment]
This is from the `robot_status_default_aggregate_issue` branch.

**Comment by JeremyZoss** [comment]
I think this is probably correct.  I now remember you sending this fix, but I neglected to patch it.  I'll send a pull request now, since you've already verified the fix.

**Comment by JeremyZoss** [comment]
Although your fix doesn't quite maintain the desired timestamp behavior.  The `aggregate` method overwrites the header with that from the `in_msg`, so the `std::max` comparison will always be checking two equal values.

The spirit of the fix is correct, but I'll probably rewrite it rather than merging in your change.

**Comment by gavanderhoorn** [comment]
Fine with me. I think I didn't spend too much time on this at the time.

I just remembered that we'd seen a similar issue and that I'd 'fixed' it.

**Comment by gavanderhoorn** [comment]
I seem to have some other fixes in my local version that also don't appear to be included in the version we imported into this repository.

Could you check whether you still have a copy of the repository we used earlier? My `isWithinRange(..)` in `industrial_robot_client/src/v2/utils.cpp` for instance is also very much different to what this repository has.

**Comment by JeremyZoss** [comment]
@gavanderhoorn : Yes, I do have a copy of the repo we were using previously.  The changes to `isWithinRange` are a bugFix that I have tracked to 2015.07.13.  Perhaps further comparisons/discussions should be handled offline, or at least not attached to this issue?

**Comment by gavanderhoorn** [comment]
Agreed.

**Comment by mmoerdijk** [comment]
Could one of you (@gavanderhoorn @JeremyZoss ) post the conclusion of this discussion? I would be interesting to know if there are other already fixed issues out there :-)

**Comment by mmoerdijk** [comment]
@JeremyZoss could you do a PR to fix this?  As you already seem to have a fix on your personal rep?

**Comment by JeremyZoss** [comment]
@mmoerdijk See PR #11 (submitted a month ago).  Let me know if you're looking for something more...

**Comment by mmoerdijk** [comment]
@JeremyZoss Sorry I did not see that PR, I tested it and it works for me. Thanks
